---
title: "Pre_Post Scale T Score Analysis"
author: "Alfieri EK & Obed Asare"
date: "2024-04-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE,message=FALSE,warning=FALSE}
library(dplyr)
library(tidyr)
library(readxl)
library(tidyverse)
library(rstatix)

# Reading Datasets
Jan21_Data <- read.csv("Jan21_Scores.csv", header = T)
May21_Data <- read.csv("May21_Scores.csv", header = T)
Dec21_Data <- read.csv("Dec21_Scores.csv", header = T)
May22_Data <- read.csv("May22_Scores.csv", header = T)

T_Scores_Col <- c(grep("_T$", names(Jan21_Data), value = TRUE))
Scales_name <- c("ResponseLevel", "AtypicalResponse", "Anxiety", "Depression", "Anger_Aggression",
            "Posttraumatic_Stress_Intrusion", "Posttraumatic_Stress_Avoidance", "Posttraumatic_Stress_Arousal",
            "Posttraumatic_Stress_Total","Dissociation", "SexualConcerns")

# T_Scores_Col <- c(colnames(Jan21_Data[,1:5]),grep("_T$", names(Jan21_Data), value = TRUE))



# This selects all columns that are not in T_Scores_Col
# Jan21_T_Scores <- Jan21_Data %>%
#   select(-any_of(T_Scores_Col))

Jan21_T_Scores <- Jan21_Data %>%
  select(any_of(T_Scores_Col))

colnames(Jan21_T_Scores) <- paste(colnames(Jan21_T_Scores), "Jan21", sep = "_")


May21_T_Scores <- May21_Data %>%
  select(any_of(T_Scores_Col))

colnames(May21_T_Scores) <- paste(colnames(May21_T_Scores), "May21", sep = "_")


Dec21_T_Scores <- Dec21_Data %>%
  select(any_of(T_Scores_Col))

colnames(Dec21_T_Scores) <- paste(colnames(Dec21_T_Scores), "Dec21", sep = "_")


May22_T_Scores <- May22_Data %>%
  select(any_of(T_Scores_Col))

colnames(May22_T_Scores) <- paste(colnames(May22_T_Scores), "May22", sep = "_")
```

# Jan21 and May21 Comparison

## Summary Statistics
```{r comment=NA,echo=FALSE}
Jan_May_21 <- list()

for (i in c(1:11)) {
  Jan_May_21[[i]] <- cbind(Jan21_T_Scores,May21_T_Scores) %>% 
    select(contains(T_Scores_Col[i]))
}

Jan_May_21 <- setNames(Jan_May_21, Scales_name)



Jan_May_21_SummaryStats <- list()

for (i in c(1:11)) {
  A <- Jan_May_21[[i]]
  B <- Jan_May_21[[i]]
  colnames(A) <- paste(colnames(A), "Mean", sep = "_")
  colnames(B) <- paste(colnames(B), "SD", sep = "_")
  MU <- A %>% apply(2,mean) 
  SD <- B %>% apply(2, sd)
  Jan_May_21_SummaryStats[[i]] <- c(MU,SD)
}
Jan_May_21_SummaryStats <- setNames(Jan_May_21_SummaryStats, Scales_name)

Jan_May_21_SummaryStats


```

## Sign Test
```{r comment=NA,echo=FALSE}
#-------------------------------------------------------------------------------

Jan_May_21_long <- list()

for (i in c(1:11)) {
  Jan_May_21_long[[i]] <- cbind(Jan21_T_Scores,May21_T_Scores) %>% 
    select(contains(T_Scores_Col[i]))%>%
    gather(key = "Scale", value = "T_Score")
}

Jan_May_21_long <- setNames(Jan_May_21_long, Scales_name)


#---------------------------------#---#-----------------------------------------


Jan_May_21_SignTest <- list()


for (i in c(1:11)) {
  Jan_May_21_SignTest[[i]] <- Jan_May_21_long[[i]] %>% wilcox_test (T_Score ~ Scale, paired = TRUE)

}

Jan_May_21_SignTest <- setNames(Jan_May_21_SignTest, Scales_name)
Jan_May_21_SignTest
``` 

# Dec21 and May22 Comparison

## Summary Statistics 
```{r comment=NA,echo=FALSE}
Dec_May_22 <- list()

for (i in c(1:11)) {
  Dec_May_22[[i]] <- cbind(Dec21_T_Scores,May22_T_Scores) %>% 
    select(contains(T_Scores_Col[i]))
}

Dec_May_22 <- setNames(Dec_May_22, Scales_name)



Dec_May_22_SummaryStats <- list()

for (i in c(1:11)) {
  A <- Dec_May_22[[i]]
  B <- Dec_May_22[[i]]
  colnames(A) <- paste(colnames(A), "Mean", sep = "_")
  colnames(B) <- paste(colnames(B), "SD", sep = "_")
  MU <- A %>% apply(2,mean) 
  SD <- B %>% apply(2, sd)
  Dec_May_22_SummaryStats[[i]] <- c(MU,SD)
}
Dec_May_22_SummaryStats <- setNames(Dec_May_22_SummaryStats, Scales_name)

Dec_May_22_SummaryStats
```

## Sign Test
```{r comment=NA,echo=FALSE}
#-------------------------------------------------------------------------------
Dec_May_22_long <- list()

for (i in c(1:11)) {
  Dec_May_22_long[[i]] <- cbind(Dec21_T_Scores,May22_T_Scores) %>% 
    select(contains(T_Scores_Col[i]))%>%
    gather(key = "Scale", value = "T_Score")
}

Dec_May_22_long <- setNames(Dec_May_22_long, Scales_name)


#---------------------------------#---#-----------------------------------------


Dec_May_22_SignTest <- list()

for (i in c(1:11)) {
  Dec_May_22_SignTest[[i]] <- Dec_May_22_long[[i]] %>% wilcox_test (T_Score ~ Scale, paired = TRUE)
  
}

Dec_May_22_SignTest <- setNames(Dec_May_22_SignTest, Scales_name)


Dec_May_22_SignTest
```

